/* Category */
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

// export const ADD_CATEGORY_PENDING = 'ADD_CATEGORY_PENDING';
// export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
// export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

// export const UPDATE_CATEGORY_PENDING = 'UPDATE_CATEGORY_PENDING';
// export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
// export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

// export const DELETE_CATEGORY_PENDING = 'DELETE_CATEGORY_PENDING';
// export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
// export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';
/* Category */

/* Post */
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

/* Post */

/* Author */
export const FETCH_AUTHOR_PENDING = 'FETCH_AUTHOR_PENDING';
export const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS';
export const FETCH_AUTHOR_FAILURE = 'FETCH_AUTHOR_FAILURE';
/* Author */
